### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled (even though it is?)

### ISSUE THREAD

**Issue by yo1nkers** [rsxdalv/tts-generation-webui#121]
![image](https://github.com/rsxdalv/tts-generation-webui/assets/113177675/77fdda39-d904-47c6-bed3-e342430a5f2b)
I have an RTX 3060. It's not detecting it. Using latest release need help.
I am confused as I thought I have installed it correctly, as I used YOUR fork of the installer.

Recieving this error;
```Traceback (most recent call last):
  File "X:\Demucs\tts-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "X:\Demucs\tts-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "X:\Demucs\tts-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "X:\Demucs\tts-webui\tts-generation-webui\src\rvc_tab\rvc_tab.py", line 68, in run_rvc
    return infer_rvc(
  File "X:\Demucs\tts-webui\tts-generation-webui\src\rvc_tab\rvc_tab.py", line 29, in infer_rvc
    get_vc(model_path)
  File "X:\Demucs\tts-webui\installer_files\env\lib\site-packages\rvc_beta\infer_batch_rvc.py", line 201, in get_vc
    net_g.eval().to(device)
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\End User\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled```

**Comment by rsxdalv** [comment]
Thanks for asking!

Yes, the fork should install it properly. I'm assuming you are using the
6.0 installer and you selected Nvidia during installation.

Also presumably none of the tabs work.

Perhaps I should make a system data generator, but for now it's only
possible to do it manually:

Using  cmd_windows.bat type `pip show torch`

That usually shows most of the issue.

**Comment by yo1nkers** [comment]
> Using cmd_windows.bat type `pip show torch`

Perhaps there's something I'm missing, or I just don't have the functioning brainpower 😅

```Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\end user\appdata\roaming\python\python310\site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, audiocraft, audiolm-pytorch, autogpt, basicsr, clean-fid, demucs, diffq, dora-search, ema-pytorch, encodec, facexlib, fairseq, flashy, functorch, gfpgan, julius, kornia, lion-pytorch, local-attention, openunmix, realesrgan, rotary-embedding-torch, suno-bark, tomesd, torchaudio, torchcrepe, torchdiffeq, torchmetrics, torchsde, torchvision, vector-quantize-pytorch, vocos, xformers```

**Comment by rsxdalv** [comment]
Interesting. It's using the global torch instead of the torch installed from the project. At first I thought that the one click installer has failed or wasn't used, but it seems that RVC is installed within the conda environment.

Although it's not ideal, I would recommend a clean install. Let me know if you need to backup or save any files or settings from the current installation.
Also, since we are suspecting an installation error, a full install log might be useful (unfortunately it can only be done by copy pasting the terminal contents manually.)

**Comment by yo1nkers** [comment]
How am I able to perform a "clean" install? Would this just be deleting the clone, and re-cloning? Or would it be a little more complicated such as removing certain site-packages manually. I have RVC and Tortoise files in tts-generation-webui\data\models

**Comment by yo1nkers** [comment]
I should be able to provide the full install log via pastebin.

**Comment by rsxdalv** [comment]
A full reinstall would be downloading the 6.0 installer, unarchiving it, and running start_windows.
Yes those models will need to be copied over after it's installed.

**Comment by rsxdalv** [comment]
Also if you want to attach a txt file or an image, etc, you can do it here directly. Pastebin works but it can be done with just GitHub.

**Comment by yo1nkers** [comment]
You'll have to excuse how slow it is for me, my speeds appear to be less than 300kbps. It makes the install a lengthy task. It's already been installing for what seems like 10 minutes 😂

I'll respond very soon with an install log.

**Comment by yo1nkers** [comment]
[install_log.txt](https://github.com/rsxdalv/tts-generation-webui/files/12309870/install_log.txt)
Isn't looking good for me.

**Comment by yo1nkers** [comment]
Upon further review it seems I might not have the correct PyTorch? or perhaps the wrong xFormers. Could this be a bug, or are there correct pip install command to use for xFormers & PyTorch? I can't really tell as it's stating "you have 2.0.1+cpu", although I believe I'd installed them with GPU.

```2023-08-10 16:38:38 | WARNING | xformers | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details```

**Comment by rsxdalv** [comment]
Oh that's unfortunate, it seems that the big downloads are failing. Then since the torch installation failed, it's using the global one which for you appears to be 2.0.1+cpu.

I see that there might be connection problems, so what I may recommend is perhaps trying with Docker. I saw another user begin work on building a container, and I will also do it later. https://github.com/xiaohai-huang/tts-generation-webui
https://github.com/rsxdalv/tts-generation-webui/discussions/117

**Comment by yo1nkers** [comment]
Would I be able to clone the repo for that docker or and run update_windows.bat? Or would I be uninstalling your repo until you've got a docker composition? Apologies for the persistance here I'm just annoyed over having to use my CPU lol

**Comment by rsxdalv** [comment]
Yeah CPU is a no go. The benefit there would be that it's a single download
that should work better. I'm not sure if he has finished it, maybe he can
link it. Otherwise, I'll make a docker image and post it, but that will
take some days.

You could try to install the right pytorch on your global install manually.

Also, if you want to keep trying, then running the conda install steps
again might work (from webui.py).

**Comment by yo1nkers** [comment]
Just to clarify, does this call for 11.7 or 11.8?

**Comment by rsxdalv** [comment]
11.7 but probably other versions might work

This gives more info:

"conda install -y -k pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit ninja git -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia"

**Comment by yo1nkers** [comment]
I think I'll wait for your personal Docker composure (if you still have intent to write one) rather than attempting to use more forks.

**Comment by rsxdalv** [comment]
This is a clean install, and it doesn't have network issues... Why can't it
just use the right pytorch with CUDA... Could you please verify with
cmd_windows pip show torch what's been installed?

Perhaps some dependency has gone crazy and breaks the pytorch. That can be
solved fixed but needs to be noticed asap.

**Comment by yo1nkers** [comment]
![image](https://github.com/rsxdalv/tts-generation-webui/assets/113177675/e054f95d-cbde-4282-aaa8-15fa23d552c6)
Here is a screenshot of the log, along with actual text.

It honestly has me quite stumped as well. I will clarify once again I am using a RTX 3060 on my desktop (which we started with) and this computer as well

```Name: torch
Version: 2.0.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\theml\onedrive\desktop\one-click-installers-tts\installer_files\env\lib\site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, audiocraft, audiolm-pytorch, demucs, diffq, dora-search, ema-pytorch, encodec, fairseq, flashy, functorch, julius, lion-pytorch, local-attention, openunmix, rotary-embedding-torch, suno-bark, torchaudio, torchcrepe, torchmetrics, torchvision, vector-quantize-pytorch, vocos, xformers```

**Comment by yo1nkers** [comment]
Will stay tuned for a response then.

**Comment by rsxdalv** [comment]
Ok, I will post as I find more information, so it's probably going to stack up some notifications, but this approach should make sense.

From what I saw, the installation script screws up pytorch.
Therefore, after the installation is done, running a command like shown in the other thread for reinstalling pytorch might work.

Why does it do it? Because one package asks for version 2.0.1 but 2.0.0 is being installed.
Since when this has been happening? It's hard to determine. Quite possibly it affects new users but not people who have installed the UI a long time ago and kept updating, because there's a few "problematic" packages that didn't break stuff before, but now they do. (And by default, it doesn't update anything that doesn't need to be updated, hence - old users might have been protected from this.)

I think I'll add some fixes for now to get the "old" working version when installing, preventing this from happening.

The real solution will be a) check the packages and stop them from messing with pytorch b) see if everything can be safely upgraded to 2.0.1 (which might not work).

**Comment by rsxdalv** [comment]
https://github.com/rsxdalv/tts-generation-webui/pull/126

Ok, this _seems_ to work. The easiest way would be a clean install, an update alone will not fix it unfortunately. (There's probably a few magical ways, but let's discuss them if bandwidth/etc is an issue, otherwise a clean install should be the best option. )

What's also interesting is that since other packages reinstalled pytorch version 2.0.0 it was harder to notice.

What I did was pin xformers @ 0.0.19, the whole project stricly uses 2.0.0 so 2.0.1 cannot be mixed in.
