### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by Renoven** [rsxdalv/tts-generation-webui#155]
This error occurs when trying to create a voice model in Bark (2nd tab)
![image](https://github.com/rsxdalv/tts-generation-webui/assets/40232761/12c3db09-dcc6-48d0-b386-8d829a9304a1)

**Comment by rsxdalv** [comment]
Hi, thanks for reaching out!

There's a long discussion here: https://github.com/pytorch/pytorch/issues/31620

It is possible that the download was corrupted. Although it sounds unlikely, this error is also not one that I have seen myself as of yet.

May I ask if there were any issues during the first run of the model, where it failed to download or similar?

**Comment by Renoven** [comment]
The problem only occurs when creating a voice file in Bark. I'll try to run it on another OC, but I think the problem is something else. When installing and updating there are errors like: "XXX uses version XXX>=XXX, but you have XXX=XXX installed". But these errors do not affect the installation. Also I don't know if it matters, but the startup is on CPU.

**Comment by rsxdalv** [comment]
Those errors shouldn't matter, they always occur because fairseq is a tiny bit abandoned. It might be due to CPU, although I'd expect a different error, not this one with the zip file error.

As a workaround I could recommend using Google Colab to make the voice files and then downloading them onto your machine. Let me know if you want to do this and need assistance.

If this was a faulty/corrupt file, the file causing this issue might be in one of the cache folders, probably /user/.cache, but that directory has many files used system-wide.

**Comment by rsxdalv** [comment]
Another user reported this error after they switched from running it as a regular user to running it as an Administrator. Perhaps that is a clue.

**Comment by Renoven** [comment]
I think I've tried running it both ways. But I will definitely try running as a non-administrator.

I would be very grateful if you could help me create a model on your computer and send it to me, or show me a way on google.

**Comment by rsxdalv** [comment]
Here's a link to colab:

https://colab.research.google.com/github/rsxdalv/tts-generation-webui/blob/main/notebooks/google_collab.ipynb

And this video does a voice clone:

https://www.youtube.com/watch?v=gYNCnltAHzY&ab_channel=FutureThinker

**Comment by Renoven** [comment]
Thank you so much for such a quick response ❤️
