### ISSUE TITLE
XTTS just released very Good quality. Consider adding it? 

### ISSUE THREAD

**Issue by Maki9009** [rsxdalv/tts-generation-webui#169]
https://huggingface.co/coqui/XTTS-v1
https://huggingface.co/spaces/coqui/xtts

Results are pretty good, i think paring it with RVC would make it even better.. its very fast also

**Comment by rsxdalv** [comment]
Thanks, I will see about adding it. Although note that the model weights
are basically **owned** by coqui, while audiocraft is somewhat unclear,
this license is borderline unusable.

From what I can see, the model is bundled inside of coqui's massive repo.
By the way, camenduru already made a Google Colab for it

Coqui Public Model License 1.0.0

https://coqui.ai/cpml.txt

This license allows only non-commercial use of a machine learning model and
its outputs.

**Comment by rsxdalv** [comment]
Ok, so yes, I tried it. To me it's quite similar to tortoise, I don't know if it's better, I would have to test and benchmark it. (Which is complicated because there's just tortoise, tortoise with deepspeed and kvcaching and others).

However the license is just a no go. If it was just the model weights it would be plausible, but it's the code as well, and it's what they have chosen themselves.

**Comment by rsxdalv** [comment]
I will close the issue, feel free to open it if they change the license.
