### ISSUE TITLE
It's not detecting my GPU

### ISSUE THREAD

**Issue by FlameinfirenBr** [rsxdalv/tts-generation-webui#192]
I'm getting
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
And i have no idea how to change it

**Comment by rsxdalv** [comment]
Check which torch is installed

**Comment by rsxdalv** [comment]
Which version

**Comment by FlameinfirenBr** [comment]
@rsxdalv 2.0.0 cu114

**Comment by Aamir3d** [comment]
Remove torch 
Pip uninstall torch
Install torch (See https://pytorch.org/get-started/locally/ )

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by FlameinfirenBr** [comment]
@Aamir3d Sane traceback and problem after doing it

**Comment by Aamir3d** [comment]
> @Aamir3d Sane traceback and problem after doing it

Please try the options in this thread https://discuss.pytorch.org/t/pytorch-installation-rtx-3060/187895/9 

Likely a torch+Cuda conflict.

**Comment by rsxdalv** [comment]
Just looking at the versions I'm not immediately certain what's up. I think I put some safeguards to prevent torch from being reinstalled after the initial environment is set up, but some project somewhere can add "torch==2.0.1" and throw the whole balance out of the window. I am a little bit leaning towards it being a more unique problem, because if you have torch+cu___ then it is the GPU enabled torch.

Additionally, installing with conda is a bit more likely to give the right results. And any time you are trying to modify or install the packages for the project, you need to use the same virtual (conda) environment. This can be done by running cmd_windows to get a terminal that has the conda environment.

**Comment by rsxdalv** [comment]
For more context, here's a different but potentially related problem: https://github.com/rsxdalv/tts-generation-webui/issues/121

**Comment by FlameinfirenBr** [comment]
@Aamir3d Tried those things and still nothing sadly
@rsxdalv #121 Has more or less the same problem that i had, but his solution did not work for me, fresh installs didn't work either

**Comment by rsxdalv** [comment]
> @Aamir3d Tried those things and still nothing sadly @rsxdalv #121 Has more or less the same problem that i had, but his solution did not work for me, fresh installs didn't work either
> 
> Edit: It's the exact same traceback, should i also post the installation log when doing a fresh install?

Installation logs are always useful!
Also, do other ai projects work for you, such as automatic 1111?

**Comment by rsxdalv** [comment]
The short answer is: you have pytorch for CPU, thus it's not using nor
detecting the GPUs.
The long answer is that it might be due to an installation issue, but it
seems to be something new in your case.

In your log I can see several unexpected things. For example, it says that
the python version is different. This normally happens only when people
don't use the one click installers. Then there's another error that:


   1. To support symlinks on Windows, you either need to activate Developer
   Mode or to run Python as an administrator. In order to see activate
   developer mode, see this article:
   https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development


I haven't seen this error in a while. But it could indicate the main
problem - maybe for your machine, it needs either developer mode or
administrator privileges for running the project. I don't remember others
reporting this, but maybe *everyone* already had developer mode, I'm pretty
sure I did. (Or this is a new windows update etc etc).

So, although there could be multiple problems at play here, I would
recommend first switching to developer mode (unfortunately it might require
a reinstall). Many projects use HuggingFace to download model weights.

**Comment by rsxdalv** [comment]
As for triton, it's not necessary but baked deep inside of the models so
removing all of the warnings about it isn't doable.
From the log, it's still running the CPU pytorch.

**Comment by rsxdalv** [comment]
Since this issue was active a few things about installation have been changed so it's hopefully working now. Additionally, I plan on adding a torch manager inside the webui to allow fixing torch issues with GPU/MPS/CPU.

If there are any more problems please reopen this issue.
