### ISSUE TITLE
Tortoise error: RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by GalenMarek14** [rsxdalv/tts-generation-webui#204]
Tortoise TTS generation error. I have no idea what is the problem this time. I did a fresh install after the last time and everything including Bark, and Audiocraft vs is working perfectly. Only Tortoise gives this error:

> Traceback (most recent call last):
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
>     output = await app.get_blocks().process_api(
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
>     result = await self.call_function(
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\blocks.py", line 1093, in call_function
>     prediction = await utils.async_iteration(iterator)
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 341, in async_iteration
>     return await iterator.__anext__()
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 334, in __anext__
>     return await anyio.to_thread.run_sync(
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
>     return next(iterator)
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\generation_tab_tortoise.py", line 165, in gen
>     yield from generate_tortoise_long(
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 199, in generate_tortoise_long
>     datas = generate_tortoise(
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 110, in generate_tortoise
>     tts = get_tts()
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\tts-generation-webui\src\tortoise\gen_tortoise.py", line 84, in get_tts
>     MODEL = TextToSpeech(
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\tortoise\api.py", line 247, in __init__
>     self.autoregressive.load_state_dict(torch.load(get_model_path('autoregressive.pth', models_dir)), strict=False)
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\serialization.py", line 797, in load
>     with _open_zipfile_reader(opened_file) as opened_zipfile:
>   File "D:\Audiocraft\AudioGenerationWebUIALL\one-click-installers-tts-6.0\installer_files\env\lib\site-packages\torch\serialization.py", line 283, in __init__
>     super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
> RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Sorry for the trouble.

**Comment by rsxdalv** [comment]
Thanks for the report. What about before, did it work before? This error
would suggest that the tortoise file is corrupted, but this file is in the
cache, not directly in the project directory. Do you still have the old
version and is it working?

**Comment by GalenMarek14** [comment]
The old version wasn't working either. I didn't record it but I think the error was the same. Reinstalling in another folder didn't solve it either.

Actually I have another Tortoise (mrq's version) working now. This one seems like comes with built-in voices and more options so I wanted to try. Are those two cross-compatible, at least for the torch and tortoise subfolders under installer_files? I can try to replace those folders with mrq version and try again?

**Comment by GalenMarek14** [comment]
I also have a question for Bark. Do long generations only work for split lines? We can't just paste long single paragraphs right? I guess this also means long sentences need to be split halfway to a second line. Is there a good setting to make voice consistent across split generations? Your examples on the main page seem very good.

For Tortoise, I tried several past commits (manual venv installation with conda, Sep 21, Sep 9, and Sep 1 commits) but the error seems persistent. Anyway if I can make Bark generations consistent then Tortoise doesn't need to work for me. No need to try hard to fix this if it's a really unique error for me alone.

Thanks again.

**Comment by rsxdalv** [comment]
> I also have a question for Bark. Do long generations only work for split lines? We can't just paste long single paragraphs right? I guess this also means long sentences need to be split halfway to a second line. Is there a good setting to make voice consistent across split generations? Your examples on the main page seem very good.
> 
> For Tortoise, I tried several past commits (manual venv installation with conda, Sep 21, Sep 9, and Sep 1 commits) but the error seems persistent. Anyway if I can make Bark generations consistent then Tortoise doesn't need to work for me. No need to try hard to fix this if it's a really unique error for me alone.
> 
> Thanks again.

Regarding bark, yes. There are multiple automations that could be done, but I didn't go that way up until now. One of the problems is that the model is limited by seconds, not words. So some "voices" could say 100, but others 150 words. For split generations that is the grand _limitation_ and _skill_ of Bark. For each generation, you can use the same "voice", like A A A A A, or let them "continue" (using each generation as a "voice" for the next one), like A A2 A3 A4 A5. But there are even more methods for that.


MRQ is the compatible, but likely to confuse users when using both. I use the model differently so the UI is a bit different. It's not on purpose, just how it is. If you train something in MRQ, you essentially get an autoregressive.pth checkpoint file that can also be used with this repo or any repo, if you know how to copy the models etc. Though this might sound strange, unless you are using this tts-generation-webui's tortoise in a specialized way, MRQ is probably preferred at this point. (This version _might_ be faster and offers easier RVC usage together but MRQ is highly specialized to tortoise.)


Now back to your case - deleting the autoregressive.pth from your cache would likely fix it. This problem is not common, but I have seen some similar reports a few times. Reinstalling the project does not clear the cache, that's why if the old version doesn't work then it's likely this file, and not the source code of this project itself.

Now for the final (TLDR) part:
Deleting the 4gb <user>/.cache/tortoise folder and letting it download ought to fix your issue. It won't affect the other models.

**Comment by GalenMarek14** [comment]
Yep, deleting autoregressive.pth solved the problem. Thank you again.

**Comment by rsxdalv** [comment]
Happy to hear that!
