### ISSUE TITLE
Best free cloning app in french ? XTTS V2 ?

### ISSUE THREAD

**Issue by gandolfi974** [rsxdalv/tts-generation-webui#217]
Hello, i'm french. i'm looking for a free cloning app ton integrate in  your webui with french voice.
- Do you have an idea ?
- is it possible to integrate XTTS coqui V2 ?
thanks

**Comment by rsxdalv** [comment]
Hi, Bark has some benefits, but it's likely that you are looking for
tortoise cloning (XTTS is a variation of tortoise).


As for XTTS, coqui has decided to use a "strong" license that makes it
unusable for this project. Unless that has or will change, it will never be
in this project.

**Comment by gandolfi974** [comment]
thanks.
- tortoise is the only free and good voice french cloning  for the moment ?
- I use Pinokio on windows and there is a webui to use XTTS V2. I want the same for ubuntu in order to modify settings easily.
https://pinokio.computer/

**Comment by rsxdalv** [comment]
> thanks.
> 
> * tortoise is the only free and good voice french cloning  for the moment ?
> * I use Pinokio on windows and there is a webui to use XTTS V2. I want the same for ubuntu in order to modify settings easily.
>   https://pinokio.computer/
>   https://www.youtube.com/watch?v=cASFP-p3sxI

Sorry for the late follow up, I'm still returning from vacation.
Tortoise is not the only one, XTTS is "free" but you are _probably_ going to infringe on the non-commercial part (and that's part of the reason I will not include it in this project).
There's also bark and bark voice cloning. Bark is "good" in the sense that it makes a life-like voice. Bark is bad in that it often disregards the prompt.
For tortoise and other models (even fairseq), you can get an extra improvement by "upscaling" the output with an RVC model. Arguably that is the best _reasonable_ TTS right now. It ought to be better than what I saw in the youtube video you linked.

**Comment by gandolfi974** [comment]
thanks. 
- i'm french and XTTS is in french not bark.
- do you have a link or tutorial for "upscaling" output with RVC model ?

**Comment by rsxdalv** [comment]
> thanks.
> 
> * i'm french and XTTS is in french not bark.
> * do you have a link or tutorial for "upscaling" output with RVC model ?

bark _purportedly_ supports French, but I understand that it's performance might not be good enough.

You can see tortoise + RVC search on youtube, there are multiple videos with different examples and depths.
https://www.youtube.com/results?search_query=tortoise+rvc

**Comment by gandolfi974** [comment]
- what do you think about this app ?  https://github.com/Mangio621/Mangio-RVC-Fork
- Do you know a free app to synchronize cloning voice with face ? For the moment i use facefusion and i want to make the modified character speak with cloning voice

**Comment by rsxdalv** [comment]
> * what do you think about this app ?  https://github.com/Mangio621/Mangio-RVC-Fork
> * Do you know a free app to synchronize cloning voice with face ? For the moment i use facefusion and i want to make the modified character speak with cloning voice

As for Mangio's fork - I think there were some good changes in it, but I do not follow what's been going on with it. They decided to avoid improving the main project due to language barrier; then the original RVC project got improvements, but Mangio was already too different and could not just "get" these improvements. Then they started asking other devs to help them. I can say that I've seen several RVC forks (I own a small fork to make it installable), and several _groups_ that are working on _their_ RVC. Myself, so far I am happy with the original RVC for this project, but you can install all of the RVCs, they certainly have their pros & cons.

The face sync, I have not done that, I'd recommend searching on youtube, and if you want to discuss it, several discord servers are quite advanced on this topic. Just as an example, camenduuru's server. There must be more but I don't know them. Some stable-diffusion themed AI servers have these discussions as well.

**Comment by rsxdalv** [comment]
I think I'll close this issue. If there's more questions or discussion, please feel free to reopen.

**Comment by fatima-falconit** [comment]
> thanks.
> 
> * tortoise is the only free and good voice french cloning  for the moment ?
> * I use Pinokio on windows and there is a webui to use XTTS V2. I want the same for ubuntu in order to modify settings easily.
>   https://pinokio.computer/
>   https://www.youtube.com/watch?v=cASFP-p3sxI

Hey @gandolfi974 
I'm currently working on a French voice cloning project and maybe I could use some help. 
Kindly reply to this quote or just ping me an email directly. Thanks!

**Comment by rsxdalv** [comment]
For reference, XTTS is now available as an extension; however the disclaimers about its license still remain. From what I know, within non-English tts space, xtts is one of the best.

**Comment by gandolfi974** [comment]
> > thanks.
> > 
> > * tortoise is the only free and good voice french cloning  for the moment ?
> > * I use Pinokio on windows and there is a webui to use XTTS V2. I want the same for ubuntu in order to modify settings easily.
> >   https://pinokio.computer/
> >   https://www.youtube.com/watch?v=cASFP-p3sxI
> 
> Hey @gandolfi974 I'm currently working on a French voice cloning project and maybe I could use some help. Kindly reply to this quote or just ping me an email directly. Thanks!

hello, i have try https://github.com/daswer123/xtts-finetune-webui but the trained french voice with default argument is not enough similar

**Comment by rsxdalv** [comment]
You can try applying RVC after that

> > > thanks.
> > > 
> > > * tortoise is the only free and good voice french cloning  for the moment ?
> > > * I use Pinokio on windows and there is a webui to use XTTS V2. I want the same for ubuntu in order to modify settings easily.
> > >   https://pinokio.computer/
> > >   https://www.youtube.com/watch?v=cASFP-p3sxI
> > 
> > 
> > Hey @gandolfi974 I'm currently working on a French voice cloning project and maybe I could use some help. Kindly reply to this quote or just ping me an email directly. Thanks!
> 
> hello, i have try https://github.com/daswer123/xtts-finetune-webui but the trained french voice with default argument is not enough similar

**Comment by gandolfi974** [comment]
thanks, 
- how can i try RVC ? i can't load my XTTS finetune model in xtts-webui,  only RVC model. my personnal model  works only with "xtts-finetune-webui".
- Is it possible to create RVC model with my TTS model ?

**Comment by rsxdalv** [comment]
* my personnal model works only with "xtts-finetune-webui".
that sounds like the result of "Slightly improved official version for finetune xtts" If the model is truly incompatible, the author should not be calling it xtts...
Either way, first you generate audio with whichever XTTS variation, then you use RVC conversion.
* Is it possible to create RVC model with my TTS model ?
No, because it will sound just like the TTS model, you have to use the original source audio to get a better result than the XTTS.

You might want to join the discord.

If the model was compatible with other XTTS projects you could use it in my webui alongside RVC.

**Comment by gandolfi974** [comment]
I have train new model.
- how i can use my model with your XTTS projects ? do you have a tutorial ?
- Same question to improve audio result with RVC
- Do you recommand a project for training french TTS ? better than XTTS-FINETUNE-WEBUI ?

thanks

**Comment by rsxdalv** [comment]
> I have train new model.
> 
> * how i can use my model with your XTTS projects ? do you have a tutorial ?
> * Same question to improve audio result with RVC
> * Do you recommand a project for training french TTS ? better than XTTS-FINETUNE-WEBUI ?
> 
> thanks

As far as I understand we have gone over these in Discord, but I will post them here too:

1. The XTTS plugins work normally without anything special (since this question was asked the plugins have been improved for easier UI)
2. RVC present in the WebUI is almost the same as other RVCs so any Youtube video should be an ok tutorial on the basics.
3. The problem with training a French TTS is the need for a base model, and I am not aware of good base models other than XTTS.
