### ISSUE TITLE
Cannot install on Mac OS with recommended setup script(s)

### ISSUE THREAD

**Issue by audiocommander** [rsxdalv/tts-generation-webui#219]
Hey, 
running on a MacBook Air M2, all latest software (sonoma), I tried various things, but I couldn't get it to install on my Mac. I was using the recommended one-click-install.
 
Aside from my other bug report where I first tried to not install miniconda again and have a preconfigured env with the correct PyTorch packages that actually work on silicon, I now tried a clean install as recommended. I get this error on start_macos.sh :

```bash
sh start_macos.sh
Traceback (most recent call last):
  File "/Users/mm/tts-webui/tts-generation-webui/server.py", line 3, in <module>
    import src.utils.dotenv_init as dotenv_init
  File "/Users/mm/tts-webui/tts-generation-webui/src/utils/dotenv_init.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Done!
```

Tried it a second time after a reboot after having deleted the installer_files directory with the same result.

...of course without any of my conda envs activated, I also get `zsh command not found: python` when I'm trying to call ```python webui.py```

Of course I could now install dotenv, but without knowing exactly which conda env your script created, I'd rather resort to trying a manual install.

After looking in python webui.py, I also noticed that for M1/M2 you're installing the torch package with CPU-only and not the one with MPS support for silicon. Is this by choice or a mistake?

Cheers!

**Comment by Shyk92** [comment]
same issue, anyone patch a fix?

**Comment by rsxdalv** [comment]
> same issue, anyone patch a fix?

Mac or Windows? Could you please include your logs. dotenv missing usually means that half of everything has failed to install. In those cases I usually need installation logs.

**Comment by rsxdalv** [comment]
> After looking in python webui.py, I also noticed that for M1/M2 you're installing the torch package with CPU-only and not the one with MPS support for silicon. Is this by choice or a mistake?

The MPS support should be resolved with the newest installer that reinstalls the correct torch version at the end within update.py

As for the install, I'm afraid there might be something that the installer does differently. My three biggest problems that the installer tries to work around are
a) getting the _right_ torch for the project and PC
b) installing modules separately so that if one fails others can still succeed (that's why there are many requirements_ files)
c) installing modules that have different dependencies together
That's why it's far from a pip install -r requirements.txt unfortunately.

I am closing this issue for now but if there are more concerns please feel free to reopen.
Hopefully the install should work now.
