### ISSUE TITLE
Mp3 option ?

### ISSUE THREAD

**Issue by ozymoz** [rsxdalv/tts-generation-webui#253]
All results are wav, can you add mp3 option ?

**Comment by rsxdalv** [comment]
Ogg files are automatically generated for several models. If you need it
for more models I can check. Since mp3 is no longer patented I could
include it though it's not as good as it's fame in 2024.
Check the /outputs please

**Comment by rsxdalv** [comment]
Now most of the models generate .ogg and .flac
I tried to switch to .mp3 but I keep getting an encoding issue from ffmpeg:
`ffmpeg stderr: [mp3_mf @ 00000213DC6DB500] nb_samples (640) != frame_size (0)`
Because of that I cannot add mp3 format as of yet.

If this is still important please inform me, meanwhile I will close this issue.
