### ISSUE TITLE
Title: Potential Upgrade to Gradio 4 for Zero GPU Hosting

### ISSUE THREAD

**Issue by polarfreez** [rsxdalv/tts-generation-webui#298]
**Description:**

I'm very interested in this project and would love to try hosting an instance on HuggingFace using Zero GPU. However, I noticed that Zero GPU only works with Gradio 4, while this project currently uses Gradio 3.

The main concern I have is whether there are any plans to upgrade this project from Gradio 3 to Gradio 4 in the future. This would be an important requirement for me to be able to host the project on HuggingFace with Zero GPU support.

Some key points:

- This project looks great and I'm excited to try it out.
- Hosting on HuggingFace with Zero GPU would be very convenient, as it would allow me to run the project without needing a GPU.
- However, Zero GPU is only compatible with Gradio 4, while this project currently uses Gradio 3.
- Will there be an upgrade to Gradio 4 in the future? Or is the project likely to remain on Gradio 3 for the foreseeable future?

I'd appreciate any information you can provide on the project's plans for a potential Gradio 4 upgrade. This would help me determine if hosting on HuggingFace with Zero GPU is a viable option. Thank you in advance for your help!

**Comment by rsxdalv** [comment]
Previously there was zero upside to upgrading to gradio 4 so I planned not
to. However, I'm still not sure if it's possible. Due to the lack of
features there's a lot of custom code that works with Gradio 3 but could
require a rewrite for the upgrade. The two versions are quite incompatible.
More so than that I'm working on developing the React based UI since I
found Gradio to be too limiting, even after all of the customization that I
did. Finally, given how this project installs with multiple requirements
files (due to packages like fairseq and omegaconf) I'm unsure it's going to
match the template for zero GPU.

Yet the Google colab should work which offers a T4 GPU and is already
compatible with this project and React UI.

**Comment by rsxdalv** [comment]
Also Thanks for informing me about this. I checked the documentation and I
can see that there are more requirements for it. I'm not certain if it's
really possible for a dedicated GPU project to easily switch because a lot
of the functions are trying to do the opposite: on desktop you want to keep
the models in cache and reduce the start time as much as possible.
Meanwhile here you want to use the GPU as little as possible. I think a
couple of models could be compatible with that right now, some are
absolutely not able to do that yet.
