### ISSUE TITLE
[FEATURE] Upgrade torch

### ISSUE THREAD

**Issue by ashleykleynhans** [rsxdalv/tts-generation-webui#309]
Any particular reason why this application needs to use torch version 2.0.0 when there are much newer releases available, such as 2.3.0?

**Comment by rsxdalv** [comment]
Yes, installation restrictions because the python package manager has
opinions about how things should be installed. Workarounds increase cost
and complexity. Also unfortunately there are times when 2.0.0 and 2.3.0
might just not be perfectly compatible.

If you need the newer torch version, it probably works and you can install
it with cmd_windows.bat terminal.
