### ISSUE TITLE
Model dropdown for Stable Audio in gradio app is empty

### ISSUE THREAD

**Issue by ashleykleynhans** [rsxdalv/tts-generation-webui#329]
No models are showing in the gradio dropdown.

<img width="1339" alt="Monosnap TTS Generation WebUI 2024-07-01 18-02-24" src="https://github.com/rsxdalv/tts-generation-webui/assets/886709/4666d894-0d16-4eb4-9bb2-9d381d593888">

**Comment by rsxdalv** [comment]
Yes!

Stable Audio due to licensing does not automatically download a model like bark etc did before.

I understand the UX needs improvements. What should I put there?
"Please download a model using the download tab" or something similar?

I am quite limited by UX & performance on the gradio side though I think I will add this to React UI too.

Basically, due to the license restrictions the model does not download automatically, and it is kept in a more-accessible folder. So less mysterious .cache and more /models/ like the other webuis.

**Comment by ashleykleynhans** [comment]
Ah yeah, I completely forgot about that.  I think it will be useful to add the message that you have suggested to prevent silly bug reports like this one :)

**Comment by rsxdalv** [comment]
Will be added in the next patch.

**Comment by ashleykleynhans** [comment]
Thank you.  I wanted to show you a token of my appreciation, but I don't see any links to sponsor the project/buy a coffee etc so you may want to consider adding those.

**Comment by rsxdalv** [comment]
That's kind!
You are the first to bring this up so I will think about it, I need to factor in taxes and accounting in advance so it will take me some time.

**Comment by ashleykleynhans** [comment]
I guess it depends on the size of the donation, some people simply register it as "gift" for tax purposes, I guess buying a coffee would count more as a gift than a GitHub sponsorship though but I am no accountant so thats just a guess.
