### ISSUE TITLE
[Feature Request]: Support for fishaudio/fish-speech-1.2

### ISSUE THREAD

**Issue by ashleykleynhans** [rsxdalv/tts-generation-webui#330]
The [fish-speech-1.2](https://huggingface.co/fishaudio/fish-speech-1.2) model is currently the number 7 trending model on Hugging Face.  It looks pretty interesting, any chance support for it can be added?

**Comment by rsxdalv** [comment]
It's very fishy, they switched their license midway from BSD-3 (open source) to CC BY 4.0 Non-commercial (comparable to leaked source code). I am checking if the code from 2 months ago is still usable at all, but I feel like they don't want people to use this model, and I understand that because it takes a huge amount of effort to develop it. 
The 1.2 model is under this license, making it legally incompatible with my repository.
There is fish audio 1 that is kind of accessible, but I am in doubts.

**Comment by rsxdalv** [comment]
On top of that - the model has always been CC BY NC, so any fine tuned models will also be CC BY NC, limiting the potential.

**Comment by ashleykleynhans** [comment]
Thanks for clarifying, sounds super shady and makes perfect sense.
