### ISSUE TITLE
RVC Connection Time Out

### ISSUE THREAD

**Issue by Sp4wnf3rk3l** [rsxdalv/tts-generation-webui#339]
Hey Mate

First of all: Thx for all the work!

I'm relatively new to this, so I hope you can help me. Every time I try to use RVC I'll get a Connection Timeout after several seconds without an error message in the console.

It only says: Press any key...
If I press one however, nothing happens.
Is there a complete log to find anywhere?

I also get some minor errors when I use the installer, i will provide a log of this after a clean reinstall. Don't know if they are part of the Problem.

So long o/ have a great day

**Comment by rsxdalv** [comment]
Status update - I confirmed that for some reason it is broken with the new installer while it still works with the old installation. (I did not check if doing a clean install with the old installer works).
After debugging several things I decided to upgrade RVC package because that is now an option.
However it requires changing torch from 2.0.0 to a newer version.
As a result I am upgrading the whole project to 2.3.1 which after many tests appears to not break everything.
Consequently I am also upgrading xformers to 0.0.27 and probably updating some projects along the way.

After torch 2.3.1 migration can be done, the new RVC module can be integrated.

**Comment by rsxdalv** [comment]
Finished upgrade, please confirm if you were able to update.

**Comment by Sp4wnf3rk3l** [comment]
Thx again! Less errrors while installing... and nice ui overhaul btw.

Just tested it but now I can't open any models in RVC. If i click the dropdown nothing happens, if i click "open location" it shows the right folder however.

**Comment by rsxdalv** [comment]
Thanks. As for the models - did you put them in separate folders or all in
the base folder? The requirement has been to put them each in a separate
folder, like /checkpoints/singer/singer.index; however, maybe with the
newer RVC I can just let people put them wherever they want.

**Comment by Sp4wnf3rk3l** [comment]
Sorry for my late reply, was on a short vacation... and another Thx! Putting the models in seperate folders did the trick. Everything I tested so far is working fine now including RVC. 

You are a mighty Tech-Priest! :D

**Comment by Sp4wnf3rk3l** [comment]
In fact I am encountering another issue: Tortoise takes forever generating autoregressive samples. With 16 samples its about or two to four minutes or so and with 256 i would guess over an hour with 256, for a sentence with 5 to six words. Is this normal?

Did some research and the only thing i could find, was ppl mentioning to upgrade the torch drivers with cuda support, what you did anyway if I recall that right. Also Cuda is marked as working anyway.

4070 / 12 GB
