### ISSUE TITLE
Install error using package

### ISSUE THREAD

**Issue by IncompetentCode** [rsxdalv/tts-generation-webui#427]
Hi there, I'm using the latest version of the installer and I got this error:

[output.log](https://github.com/user-attachments/files/17985953/output.log)

I have the CUDA 11.8 SDK/Runtimes installed and am running Python 3.10.11 if that matters. 

Are there other prereqs I need for the installer?

I did try running the bat file as administrator and I got a different error:

```
Starting init app (version: 0.0.6)...


Checking conda installation...
>conda --version
conda 24.11.0

Linking to tts-generation-webui repository
>git init -b main
Initialized empty Git repository in C:/Windows/System32/.git/
>git remote add origin https://github.com/rsxdalv/tts-generation-webui
fatal: detected dubious ownership in repository at 'C:/Windows/System32'
'C:/Windows/System32' is owned by:
        NT SERVICE/TrustedInstaller (S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)
but the current user is:
        COMPUTER/USER (S-1-5-21-2862195375-317521398-141045455-1001)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Windows/System32
Command failed with exit code 128
Failed to init the app, exiting...
Press any key to continue . . .
```

**Comment by rsxdalv** [comment]
Thanks, for the error code. It seems to be an issue with conda. How much RAM do you have? Also, please don't run it as administrator, because then it tries to install to system 32 folder.
`Collecting package metadata (repodata.json): done
Solving environment: | Error during installation: Command failed with exit code 3221225477`

**Comment by rsxdalv** [comment]
Perhaps running it again normally will work but I'm unsure about that.

**Comment by IncompetentCode** [comment]
Hi there, I have 128GB of RAM and sitting at around 20-40% utilization. I did try running it again not as administrator and that just returns error code 1. I can get that output for you if that'd be helpful.

**Comment by rsxdalv** [comment]
Yes please, although I'm still a bit lost. As for the versions and installing - this installer should install _everything_, conda, python, git, cuda libraries, nodejs, pytorch, ffmpeg and even MSVC compiler. If you like the idea, you could also try a more manual installation.

**Comment by IncompetentCode** [comment]
```"Checking if the Micromamba/Conda environment is already installed."
"Micromamba/Conda environment already installed in D:\Voice+Text\tts-generation-webui-main\installer_files\env, skipping installation"
vswhere is installed, checking for Visual Studio Build Tools installation...
Visual Studio Build Tools is installed, continuing...


Starting init app (version: 0.0.6)...


Checking conda installation...
>conda --version
conda 24.11.0

Pulling updates from tts-generation-webui
>git pull
Already up to date.
Ensuring that python has the correct version...
Checking python version...
>python --version > installer_scripts/.python_version

Applying conda config...
  Checking if Torch is installed...
  Major version update detected. Upgrading base environment
  Using saved GPU choice: NVIDIA GPU
>conda install -y -k conda-forge::uv=0.4.17 conda-forge::vswhere  conda-forge::postgresql=16.4 conda-forge::nodejs=22.9.0 conda-forge::ffmpeg=4.4.2[build=lgpl*] pytorch[version=2.3.1,build=py3.10_cuda11.8*] pytorch-cuda=11.8 torchvision torchaudio cuda-toolkit ninja  -c pytorch -c nvidia/label/cuda-11.8.0 -c nvidia
D:\Voice+Text\tts-generation-webui-main\installer_files\env\lib\site-packages\conda\base\context.py:200: FutureWarning: Adding 'defaults' to channel list implicitly is deprecated and will be removed in 25.3.

To remove this warning, please choose a default channel explicitly with conda's regular configuration system, e.g. by adding 'defaults' to the list of channels:

  conda config --add channels defaults

For more information see https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/use-condarc.html

  deprecated.topic(
Channels:
 - pytorch
 - nvidia/label/cuda-11.8.0
 - nvidia
 - defaults
 - conda-forge
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch==2.3.1[build='^py3.10_cuda11.8*$']

Current channels:

  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia/label/cuda-11.8.0
  - https://conda.anaconda.org/nvidia
  - defaults
  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Error during installation: Command failed with exit code 1
Command failed with exit code 1
Failed to init the app, exiting...```

**Comment by rsxdalv** [comment]
Actually, this appears to be linked. https://github.com/rsxdalv/tts-generation-webui/issues/428

I think they deleted something/removed old versions. 

However, I can still find it here:

https://anaconda.org/pytorch/pytorch/files?page=4&sort=length&sort_order=desc

<html>
<body>
<h4 class="modal-title" id="myModalLabel" style="box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; color: rgb(34, 34, 34); font-family: &quot;Museo Sans Rounded&quot;, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-style: normal; font-weight: 400; line-height: 1.4; text-rendering: optimizelegibility; font-size: 1.4375rem; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">win-64/pytorch-2.3.1-py3.10_cuda11.8_cudnn8_0.tar.bz2</h4><p class="subheader" style="box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; font-family: &quot;Museo Sans Rounded&quot;, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-size: 16px; font-weight: 400; text-rendering: optimizelegibility; line-height: 1.4; color: rgb(111, 111, 111); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">No Description</p><div style="box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(34, 34, 34); font-family: &quot;Museo Sans Rounded&quot;, &quot;Helvetica Neue&quot;, Helvetica, Roboto, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Uploaded | Tue May 28 23:17:43 2024
-- | --
md5 checksum | e1dbea35e934eea56700175b9f63911e
arch | x86_64
build | py3.10_cuda11.8_cudnn8_0
constrains | cpuonly <0
depends | blas * mkl, filelock, intel-openmp, jinja2, libuv >=1.44.2,<2.0a0, mkl 2021.4.*, networkx, python >=3.10,<3.11.0a0, pytorch-cuda >=11.8,<11.9, pytorch-mutex 1.0 cuda, pyyaml, sympy, typing_extensions
license | BSD 3-Clause
license_family | BSD
machine | x86_64
operatingsystem | win32
platform | win
subdir | win-64
target-triplet | x86_64-any-win32
timestamp | 1716916679647

</div>
</body>
</html>

So it seems that the fix is to get it to find the package. Potentially could be an issue with anaconda package repository. It might be possible to just use another, newer version (although 2.3.1 has been _the best_ with 2.4 being slow and 2.5 starting to break)

**Comment by rsxdalv** [comment]
I hope that this issue has been fixed with the fix that I pushed out last week. I have not seen more reports of this issue, and I was able to confirm the bug and report it to conda team as well; meanwhile implementing a workaround.
