### ISSUE TITLE
Opensource License

### ISSUE THREAD

**Issue by jasonmhead** [rsxdalv/tts-generation-webui#47]
Hello; 
Could this repo get a MIT or Apache2 license on it?

That could free people up to use and build upon it freely and comfortably.

**Comment by rsxdalv** [comment]
Hi, I understand completely!

I am aiming for MIT/Apache 2.0 compatibility, I believe I haven't included any libraries that force a copyleft license, although, honestly, it feels like a minefield. With the one-click-installers I am a bit more concerned if they are _MITtable_.

Let me take a look at it.

**Comment by rsxdalv** [comment]
This is one problem: lameenc should probably get excluded (even though it's "parent" is MIT, but I'm pretty sure it's not even being used). Maybe by modifying the install command/setup to not install this package would the whole "software" fall within MIT.

However, this is a good example - even while my code would be MIT, the second you run `pip install` etc, you are into GPL territory.

```
(C:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env) C:\Users\admin\Desktop\one-click-installers-tts-main>pip show lameenc
Name: lameenc
Version: 1.4.2
Summary: LAME encoding bindings
Home-page: https://github.com/chrisstaite/lameenc
Author: Chris Staite
Author-email: chris@yourdreamnet.co.uk
License: GPLv3
Location: c:\users\admin\desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages
Requires:
Required-by: demucs

(C:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env) C:\Users\admin\Desktop\one-click-installers-tts-main>pip show demucs 
Name: demucs
Version: 4.0.0
Summary: Music source separation in the waveform domain.
Home-page: https://github.com/facebookresearch/demucs   
Author: Alexandre Défossez
Author-email: defossez@fb.com
License: MIT License
Location: c:\users\admin\desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages
Requires: diffq, dora-search, einops, julius, lameenc, openunmix, pyyaml, torch, torchaudio, tqdm
Required-by: audiocraft

(C:\Users\admin\Desktop\one-click-installers-tts-main\installer_files\env) C:\Users\admin\Desktop\one-click-installers-tts-main>pip show audiocraft
```

**Comment by rsxdalv** [comment]
Ok, python lameenc will be LGPL for future releases (so if you want to have LGPL right now for lameenc package you have to install it manually).
Next, diffq currently is CC BY NC 4.0 but it appears that it will become optional, if the demucs version is new enough it will work, otherwise do `pip install demucs` for the new version and then `pip uninstall diffq` if it still is present.
Finally, encodec has a MIT license for newer releases but it also has to be installed manually, the currently installed version 0.0.1 has CC BY NC 4.0 license.

With that in mind, we are heading for an **actually** plausible MIT license for the project, even after pip install.
