### ISSUE TITLE
[Feature Request] Choose which Directory Cache and Models go to

### ISSUE THREAD

**Issue by MiYakuGaming** [rsxdalv/tts-generation-webui#68]
Is it possible to choose where cached stuff goes to?
My OS Install or C: is becoming full and I ordered a dedicated external HDD for AI stuff.
For example, the models go to my user cached directory, I want everything to go to my separate HDD in a certain folder.

**Comment by rsxdalv** [comment]
Yes, I'll try to document it in the readme.
Right now there are 3 locations.
Hugging Face cache
Torch Hub cache
data/models/ inside the tts-generation-webui directory

The caches are good because they are shared between installations and even
between different UIs/projects.

For HuggingFace cache, these are the instructions:
The <CACHE_DIR> is usually your user’s home directory. However, it is
customizable with the cache_dir argument on all methods, or by specifying
either HF_HOME or HUGGINGFACE_HUB_CACHE environment variable.

For Torch Hub cache:

The locations are used in the order of

   -

   Calling hub.set_dir(<PATH_TO_HUB_DIR>)
   -

   $TORCH_HOME/hub, if environment variable TORCH_HOME is set.
   -

   $XDG_CACHE_HOME/torch/hub, if environment variable XDG_CACHE_HOME is set.
   -

   ~/.cache/torch/hub


Later today I can take a look at adding this inside the settings tab and
testing.

**Comment by rsxdalv** [comment]
Good point. The UI approach should make it easier to manage.
Also it's a small risk, though depending on how you update, you can damage
your config. Maybe I'll delay releasing this just a little bit to first
make the config future compatible.

**Comment by bdashore3** [comment]
Hi there, I'd also like to add to this regarding RVC. Can there be a model dropdown for selecting one in `data/models`? This is present in audio-webui, but I like this webui a lot more since it has options for tortoise.

**Comment by rsxdalv** [comment]
Yes, though I've been focusing on tutorials recently, another round of UX
improvements is planned.

**Comment by rsxdalv** [comment]
> Hi there, I'd also like to add to this regarding RVC. Can there be a model dropdown for selecting one from `data/models`? This is present in audio-webui, but I like this webui a lot more since it has options for tortoise.

https://github.com/rsxdalv/tts-generation-webui/pull/77

**Comment by rsxdalv** [comment]
Added in https://github.com/rsxdalv/tts-generation-webui/pull/90

**Comment by MiYakuGaming** [comment]
I have tried setting the paths in the Settings tab and applying the changes after a restart, but it never changes anything.
I have my cache and everything in a separate External HDD because I run out of space in my user folder and tried changing the directories to the External HDD.
I still get downloads for my user directory .cache.

How do I do this?

**Comment by rsxdalv** [comment]
Latest update: https://github.com/rsxdalv/tts-generation-webui/commit/a65307efa55a96c00860a36f4730b2e40bd55775

**Comment by rsxdalv** [comment]
Closing as completed. Please reopen the issue if the issue persists.
